### ISSUE TITLE
Load error in test scripts

### ISSUE THREAD

**Issue by hmms117** [Kuanhao-Chao/splam#3]
Hi,

Thanks for creating a very promising tool. The default test scripts in the `test` folder seems to fail. Both `script_alignment.sh` and `script_annotation.sh` seems to fail when loading the test fasta file.

```bash
>JUNC00000000   ['>JUNC00000000', '14', 'rna-XM_047422581.1,rna-XM_017014169.2,rna-XM_011517665.3,rna-XM_024447369.2,rna-XM_011517662.4,rna-XM_017014171.2,rna-XM_047422579.1,rna-XM_011517664.4,rna-XM_017014172.2,rna-NM_001378090.1,rna-XM_011517660.3,rna-XM_011517659.3,rna-XM_011517666.3,rna-NM_182905.6']
Traceback (most recent call last):
  File "splam/bin/splam", line 8, in <module>
    sys.exit(main())
  File "splam/lib/python3.10/site-packages/splam/main.py", line 214, in main
    junction_fasta = parse.concatenate_donor_acceptor_fasta(donor_fasta, acceptor_fasta, verbose)
  File "splam/lib/python3.10/site-packages/splam/parse.py", line 184, in concatenate_donor_acceptor_fasta
    d_splits = eles[3].split("(")
IndexError: list index out of range
```

Do I need to change the delimiters or reformat the FASTA file?

Looking forward to testing the tool

**Comment by Kuanhao-Chao** [comment]
Hi @hmms117,

What is the version of Splam on your device? I tested both scripts and did not encounter the same problem. You can update Splam to the latest version (https://github.com/Kuanhao-Chao/splam/releases/tag/v1.0.8) and then try running the two scripts again.

Kuan-Hao

**Comment by hmms117** [comment]
Thank you - I just did a git clone, but will try the release version now.
