### ISSUE TITLE
No "-A" parameter in "splam score" command in mouse specie

### ISSUE THREAD

**Issue by Mingzhuge** [Kuanhao-Chao/splam#5]
Hi,
Actually, I met a problem in running “splam score” with mouse specie even in example given by the website (https://ccb.jhu.edu/splam/content/generalization.html): 

Command:
splam score -A GRCm39_assembly_report.txt -G mouse_chr19.fa -m ../model/splam_script.pt -o tmp_out_generalization tmp_out_generalization/junction.bed

Come out:
error: unrecognized arguments: -A tmp_out_generalization/junction.bed.

I used the "splam score -h" to check the parameter: there is no "-A". Is there any problem?

The version is “splam  1.0.9”. I also checked the 1.0.10, the same error.

Thank you.

**Comment by Kuanhao-Chao** [comment]
Hi @Mingzhuge , 

We've updated Splam to version 1.0.10, removing the '-A' argument which was previously required to specify chromosome lengths. Splam now automatically calculates these lengths from the fasta file. Please install the latest version and test it using the scripts in the 'test/' directory. We've also updated the documentation to reflect this change. 

Kuan-Hao
